
# Values which are supplied to the Helm for the Kubernetes deployment
rasax:
  name: gcr.io/rasa-platform/rasa-x-ee

app:
  name: gcr.io/rasa-platform/carbon-bot-actions

nginx:
  service:
    port: 80
    type: NodePort

ingress:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "carbon-bot"
    networking.gke.io/managed-certificates: "rasa-bots-certificate"
  hosts:
  - host: carbon.rasa-bots.com
    paths:
    - /

securityContext:
  fsGroup: 0
